### ISSUE TITLE
myGLOS passwork reset not working for Scott M

### ISSUE THREAD

**Issue by beckypearson** [glos/user_queries#15]
Scott Moegling, Scott_Moegling@clevelandwater.com, is having problems with resetting his password. He uses Explorer as a browser. His address popped right up, but he didn't get any automated email with a reset link. The screen shots show the progression: 

![image](https://user-images.githubusercontent.com/20344870/27087285-96bccfa4-5022-11e7-8fbc-57e648a2e7d6.png)
![image](https://user-images.githubusercontent.com/20344870/27087306-a45af4c4-5022-11e7-9119-470f8c44fdd8.png)
![image](https://user-images.githubusercontent.com/20344870/27087322-af0b3f1e-5022-11e7-8928-fa935718674b.png)

**Comment by beckypearson** [comment]
Scott created a new account and said everything is fine...issue resolved.

**Comment by kknee** [comment]
@beckypearson did this query from scott come in via the feedback form or did he contact you directly?

**Comment by beckypearson** [comment]
@kknee He contacted Kristin directly, and she forward it on to me.
