### ISSUE TITLE
Russ Miller inquiry - new buoy site function: UMBio

### ISSUE THREAD

**Issue by kristinschrader** [glos/user_queries#21]
"I'm getting a 404 from the UMBIO, GLRCmet  forwarding link.... Will that buoy be transitioned? "

**Comment by kkoch** [comment]
I am not clear on where he is getting the 404.  All looks well in the portal and I'm not sure what the GLRCmet forwarding link is.

**Comment by kristinschrader** [comment]
These are all things he experienced when trying to use the new buoy site as
he did the old buoy site

Kristin Schrader
Great Lakes Observing System
734-741-2294
glos.us <http://www.glos.us>


Like our Facebook page
<https://www.facebook.com/GreatLakesObservingSystem/?ref=aymt_homepage_panel>
Follow our Twitter feed <https://twitter.com/GLOSystem>

**Comment by kkoch** [comment]
okay well..... umbio isn't on the new site for some reason.  So maybe he put it after the station link so he would get a 404?  Asking @gcutrell why umbio isn't on glbuoys in case thats the real question.

**Comment by kristinschrader** [comment]
I think that probably is the real question

**Comment by kkoch** [comment]
issue has been submitted to glbuoys repository

**Comment by gcutrell** [comment]
I can add it next week. A station that slipped through the cracks since it isn't in a Great Lake.

**Comment by gcutrell** [comment]
Completed
