### ISSUE TITLE
GLOS Data Retrieval 

### ISSUE THREAD

**Issue by beckypearson** [glos/user_queries#28]
Tad and Kelly concur that she can make a dap request to TDS: 
TDS is my thought, too. Kathy, please reach out to Kate to find out how many locations she's looking at. If it's just one to a few, we can help her structure a TDS query along the lines of (e.g.)
 
 
http://tds.glos.us/thredds/dodsC/glos/glcfs/archiveall/erie/ncfmrc-2d/Lake_Erie_-_Nowcast_-_2D_-_All_Years_best.ncd.ascii?time[35080:1:61360],wvh[35080:1:61360][30:1:30][50:1:50]
 
(this returns all waveheight values 2014-2016 at cell (30,50))

Original Email Query......................................

Dear Ms. Schrader, 

My name is Kate Laramie and I work with the Michigan Tech Research Institute. One of our projects is utilizing Great Lakes Observing System data to retrieve wave height information for Lake Erie for over 400 different dates and time periods from 2014-2016. 

I'm currently entering each individual date and time into the GLOS Point Query Tool for the Great Lakes Coastal Forecasting System individually, and I was wondering if there might be a "back door" into the system into which I could retrieve wave data for multiple dates/times at once. 

I was hoping that you might be able to put me in contact with someone who could answer my question? 

Thank you very much for your time! 

Best,

-- 
Kate Laramie
Intern 
Michigan Tech Research Institute (MTRI) 
Michigan Technological University

**Comment by kkoch** [comment]
She is looking for 24 locations.  @tslawecki : is there a simple instruction you can provide so she can build the query?  See her response below:

>>> "Thanks for looking into this for me! I have 24 individual locations that we are interested it (I have the lat long for each), and at each of these locations I'm interested in wave data for multiple dates, and times. Would it be possible to build a query reporting values for 2014-2017 for each of these locations? (I apologize, I think I originally said we were interested in data through 2016, but I was incorrect)."

**Comment by beckypearson** [comment]
@tslawecki   Just moving this up, cuz it isn't closed.

**Comment by tslawecki** [comment]
I need her e-mail. She can use the attached spreadsheet to find the x and y values to substitute in to the TDS query ...
[GLOS_Erie_POM_LL_Lookup-20171127.xlsx](https://github.com/glos/user_queries/files/1506383/GLOS_Erie_POM_LL_Lookup-20171127.xlsx)

**Comment by kkoch** [comment]
Sorry I should have closed this.  Per my last convo with her about a week ago > Hi Kathy,  

"I'm sorry I misunderstood the query you sent earlier. Thanks for the help! I should be able to figure things out from here. "

But I will forward her Tad's spreadsheet as well.
