### ISSUE TITLE
Boaters Lake Selection Tool Broken

### ISSUE THREAD

**Issue by beckypearson** [glos/user_queries#29]
I tried this morning and it isn't working in Chrome on my Dell. 

Mark T. 's email below: 
Hi Becky,
Here’s a bookmark I had for the GLOS site. It seems hung-up to me, and keeps asking me to enter a lake. Just thought you could pass it along to someone. Here’s the link I was using:
http://boaters.glos.us/?homepage=POM_SST
 
Mark Torregrossa
MLive

**Comment by kknee** [comment]
@beckypearson that's an odd link to the boaters tool.  We have defined bookmarks by lake not by dataset.  That link does not contain a lake.   I wonder if that is a really old bookmark from the previous iteration?

**Comment by kknee** [comment]
these are the types of links that can direct users to a specific lake: 
http://boaters.glos.us/#lake-superior
http://boaters.glos.us/#lake-erie

**Comment by beckypearson** [comment]
@kknee  You are right. I don't know how he got that link either.  Just clicking through, http://boaters.glos.us, I was able to pull up the data by lake. I will email Mark and ask him to try that link. 

Becky

**Comment by tslawecki** [comment]
I expect that he had an old (data.glos.us/boaters) link that got redirected to boaters.glos.us.



I was looking into this too, and have three notes:



1) Temperature is currently not shown in boaters, so perhaps send him this link and ask if it suits:



  http://portal.glos.us/?map=NDM3MTA0YzktNjI2Yi00M2Y1LTgzOTgtMDNkOGFlZWIzYWVhOnRlbXBlcmF0dXJl&name=temperature



2) In boaters' view, only enable OK in lake selector when a lake is selected? (include in boaters' update)



3) In data portal, add "showing 1..10 of xxx" to legend box in map view or similar?



________________________________

**Comment by beckypearson** [comment]
@tslawecki, will do. I will send Mark that link.  Thanks much!

**Comment by beckypearson** [comment]
Mark wrote back: I got it from a bookmark I had made a long time ago.
