### ISSUE TITLE
Request for Buoy data for 2017 (UTLCP)

### ISSUE THREAD

**Issue by kkoch** [glos/user_queries#30]
User question 12/5/17 @ 11:30am >

Is there a way we can get the data set from this buoy for the 2017 season?

Title   
Little Cedar Point buoy (utlcp) [out of water for the season] 
Date  
2015-05-01T14:45:00 
Date type  
Publication: Date identifies when the resource was issued 
Presentation form   
Digital map: Map represented in raster or vector form 
Abstract  
Researchers at the University's Lake Erie Center sensors monitor blue-green algae. Missions of the Center include researching environmental conditions in Maumee Bay and western Lake Erie as well as discerning linkages among land-use practices, water quality, habitat, economics, natural resources, sustainability, and environmental and public health. The UT HAB Buoy is sponsored by the Ohio Board of Regents and the University of Toledo. 
Purpose  
Continuous in-situ observations of water surface conditions. 
Status  
On going: Data is continually being updated 
 
Thank you,

Pamela Struffolino
Research Operations Manager
Lake Erie Center/Stranahan Arboretum
419-530-8360
Fax: 419-530-8399

**Comment by kkoch** [comment]
My response > 

Since we are off season, and since UTLCP is one the buoys in our HABs network of stations, the easiest way is to go to our HABs viewer.  http://habs.glos.us/stations

1) Select "Little Cedar Point" from the left Stations nav bar
2) Click on the Parameter you are interested in (e.g., Water Temperature) 
3) The bottom of the screen will show recent water temperature data, but you can change the start time to 06/06/2017 (when this buoy went in the water for the season). Click the 'refresh plot' button.
4) Then to download the data there is a small menu (three horizontal lines) to the top right of the chart.  This gives you several download options, e.g., to .csv.

If that doesn't work for you, let me know what specific parameter(s) or format(s) you are looking for and I'll see what I can get for you.

**Comment by kknee** [comment]
also, this buoy is on TDS, and data available via:

opendap: http://tds.glos.us/thredds/dodsC/buoy_agg/utlcp/utlcp.ncml.html

**Comment by kkoch** [comment]
@kknee true.... do we have some sort of cheat sheet we could provide to end users on how to extract data from TDS?

**Comment by tslawecki** [comment]
See https://github.com/glos/IoH2O/wiki/Buoy-data-via-OPENDAP?


________________________________

**Comment by kknee** [comment]
@kkoch we don't and we probably should.  We get these types of requests often enough.  You can download ascii from the link I provided above, but it's a bit unwieldy for the amount of data she wants, and time would have to be converted to a date time.

There is a data download tool on our OceansMap roadmap, so when that gets finished we'll make sure it gets into the GLOS portal.  It will be more than the simple CSV download currently available from the plot.

**Comment by kknee** [comment]
i stand corrected, we do have documentation!

**Comment by kkoch** [comment]
Ah where's my "like" button.  Thanks!
