### ISSUE TITLE
Point query request

### ISSUE THREAD

**Issue by kristinschrader** [glos/user_queries#32]
Hello,
I am interested in using your point query tool. I have about 40-50 locations in Lake Erie and want to find water temperatures from certain dates in 2014 (these dates vary for each location). Is there an easy way to use your point query tool to obtain this location-date data? (Or alternatively, is there a way to put in multiple locations at the same time? If there is, I could just select all the dates and then write an R script to select the dates I want for each location). 
Thanks
-Helen  	hbontrager@usgs.gov

**Comment by beckypearson** [comment]
You can not search for multiple locations in one query with the point query tool but it supports permalinks that allows you to download data from the server without using the point query tool. You would want to first download the data for one station and check "Display CSV/Tab in browser" and then download. You will get something like this in the address bar which is your permalink for that query: http://data.glos.us/glcfs/glcfsps.glos?lake=erie&i=-81.4856&j=42.1432&v=temp&st=2018-03-01:00:00:00&et=2018-03-03:00:00:00&rdepth=0&u=e&order=asc&pv=1&tzf=-4&f=csv

This query is pulling surface water temperature from a random location in Lake Erie. In your program change the location and start/end date time (if needed) for each location and then download data from that new permalink that was created. You could make a loop to go through each location and save each download with a unique file name.
