### ISSUE TITLE
User query on buoy status in Portal

### ISSUE THREAD

**Issue by kkoch** [glos/user_queries#33]
From: Robert Drongowski [mailto:bobd@umich.edu] 
Sent: Thursday, May 10, 2018 4:38 PM
To: dmac@glos.us
Subject: [GLOS DMAC] Buoy

When are you putting buoy in Lake Erie, western basin!
Quick, I need it in.  Very useful.  Hurry.

**Comment by kkoch** [comment]
Responded to user and verified that he is interested in 45165 status (still out of the water for the season).

Since this is a LimnoTech supported buoy, checking with @gcutrell on timing and will get back to Bob.

**Comment by gcutrell** [comment]
Deployed 5/15/2018 at 6PM.

**Comment by kkoch** [comment]
I let Bob know.
