### ISSUE TITLE
Cleveland State Student Research Group query

### ISSUE THREAD

**Issue by kkoch** [glos/user_queries#37]
From: Beebe, Olivia [mailto:beebeoh@miamioh.edu]
Sent: Wednesday, September 12, 2018 1:00 PM
To: dmac@glos.us<mailto:dmac@glos.us>
Subject: [GLOS DMAC] Cleveland State Student Research Group

To whom this may concern,

My name is Olivia Beebe and I'm taking an Entrepreneurship class at Cleveland State.  I'm part of a team project trying to develop a service/product to help reduce the harmful algae blooms in Lake Erie.  Our idea is an ultrasonic devices for the lake that would be able to monitor the signs of new growth in the blooms and activate itself to break them apart before they get a chance to overwhelm the waterways.  We are still in the very early stages of our project but hope to create something that may benefit us all.  I'm reaching out to you for feedback on our idea.  I was reading about your organization and it's network for monitoring the lake conditions.  Hypothetically, could this device be useful is the network you've created?  Do you think it could be useful to anyone in the business of conserving Lake Erie?  Any kind of feedback, good or bad, is greatly appreciated.

Thank you for your time,

Olivia Beebe
Cleveland State University
Biomedical Engineering MS
Class of 2020

**Comment by kkoch** [comment]
John Bratton replied on Sept 14 >

Hi Olivia,

Thanks for reaching out—that’s an interesting idea. I’m not sure it would work on a water body the size of Lake Erie, but I know there have been similar technologies developed for smaller water bodies like drinking water reservoirs and areas around swimming beaches.

Below are some related links that I hope will be helpful.

--John

https://www.researchgate.net/publication/282055074_Ultrasonic_Treatment_of_Algae_in_a_New_Jersey_Reservoir_In_Press
https://www.ncbi.nlm.nih.gov/pubmed/28633833
http://www.dtic.mil/dtic/tr/fulltext/u2/1037253.pdf
https://www.epa.gov/nutrient-policy-data/control-and-treatment
https://conference.ifas.ufl.edu/aw13/Presentations/2-Wednesday/Grand%20Floridian/Session%208b/0300%20Whatley.pdf
http://www.mdpi.com/2073-4441/9/12/915/pdf
_____________________________________
John F. Bratton, Ph.D.
Senior Scientist
501 Avis Drive, Ann Arbor, MI  48108
Office: 734-332-1200     email:jbratton@limno.com<mailto:jbratton@limno.com>
LimnoTech           www.limno.com<http://www.limno.com/>
Water Environment | Scientists Engineers

**Comment by beckypearson** [comment]
Resent John's response to Olivia
