### ISSUE TITLE
Test issue for training

### ISSUE THREAD

**Issue by kristinschrader** [glos/user_queries#4]
This is the place a question would go as described by user. It could have screen shots. It could be a copy and pasted email.

**Comment by kristinschrader** [comment]
Here's an update to the original issue.

**Comment by kristinschrader** [comment]
Good bye, issue.

**Comment by kknee** [comment]
awww, you didn't even let us respond!

**Comment by kristinschrader** [comment]
changing for exercise

**Comment by kristinschrader** [comment]
changing to test milestone
