### ISSUE TITLE
Historic and Current Data Request

### ISSUE THREAD

**Issue by beckypearson** [glos/user_queries#5]
Hello,

My name is Kenzie Cable and I am currently getting my masters degree at the University of Nottingham in England. I am from West Virginia and worked at the WVDEP before pursuing my masters. For my dissertation I am very interested in looking at the correlation between decreased dissolved oxygen concentration and the increased atmospheric temperatures from the past till now for Lake Erie. I have been in contact with the EPA & NOAA but am finding it very difficult to talk to one person that can help me.

Im looking for information such as, how many buoys are in lake Erie that could give dissolved oxygen levels? Is there data that goes back to the 1970-80s? Of the buoys that have DO, at what depths? Do you also have temperature data for these same buoys, and at different depths? 

Thank you,
Kenzie Cable

**Comment by kkoch** [comment]
I have forwarded to DMAC.  Tad doesn't think we have anything that goes back that far for that part of the request, but I'm also going to check with Ed to see if he has any thoughts.  (NOTE: We do have an old relational database that is not yet in THREDDS, but again, don't think it goes back to the 70's/80's.)

**Comment by beckypearson** [comment]
Kathy, how old is that relational DB? I haven't closed the loop with Kenzie yet.

**Comment by kknee** [comment]
the data on THREDDS only goes back to 2015, but we do have DO and surface temperature:

http://tds.glos.us/thredds/catalog/glos/habs/lakes/catalog.html

**Comment by beckypearson** [comment]
I pointed Kenzie to the THREDDS catalog and the NDBC historic buoy data site.
